# Site settings
title: 손끝으로 만드는 세상
description: 'IT/프로그래밍/부동산 이것저것 하는 블로그'
url: 'https://inasie.github.io'
baseurl: '/'
google_analytics: 'UA-129074475-2'
disqus_shortname: 'inasie-github-io'

author:
  name: 'inasie'
  email: inasie@naver.com
  twitter_username:
  facebook_username:
  github_username: inasie
  linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

font_heading: "'Roboto Slab', 'Nanum Gothic', Helvetica, Arial, sans-serif"
font: "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-include-cache', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js
